name: MrzBarcodeScanner
description: A Flutter project to scan MRZ and barcodes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_ocr_sdk: ^2.0.3
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.0
  shared_preferences: ^2.1.1
  camera: 
    path: ./camera/
  share_plus: ^10.0.2
  url_launcher: ^6.1.11
  flutter_exif_rotation: ^0.5.1
  flutter_lite_camera:
  flutter_barcode_sdk: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/icon-about-gray.png
    - images/icon-about-orange.png
    - images/icon-arrow-green.png
    - images/icon-arrow-orange.png
    - images/icon-camera.png
    - images/icon-delete.png
    - images/icon-history-gray.png
    - images/icon-history-orange.png
    - images/icon-home-gray.png
    - images/icon-home-orange.png
    - images/icon-image.png
    - images/image-mrz.png
    - images/logo-dlr.png
    - images/default.png
    - images/icon-capture.png
