name: barcodescanner
description: A Flutter project that demonstrates how to build a cross-platform barcode scanner app with Dynamsoft Barcode Reader.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_barcode_sdk: ^3.0.1
  image_picker: ^1.0.0
  shared_preferences: ^2.1.1
  camera: ^0.10.6
  share_plus: ^10.0.2
  url_launcher: ^6.1.11
  flutter_exif_rotation: ^0.5.1
  flutter_lite_camera: ^0.0.1
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - images/icon-about-gray.png
    - images/icon-about-orange.png
    - images/icon-arrow-green.png
    - images/icon-arrow-orange.png
    - images/icon-camera.png
    - images/icon-delete.png
    - images/icon-history-gray.png
    - images/icon-history-orange.png
    - images/icon-home-gray.png
    - images/icon-home-orange.png
    - images/icon-image.png
    - images/icon-capture.png
    - images/image-barcode.png
    - images/logo-dbr.png
    - images/default.png
    
